apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - image: vamsichunduru/web-app:bug
        name: web-app-container
        imagePullPolicy: Always        
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080